name: Production CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-production:
    name: Dummy Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Simulate Production Deployment
        run: |
          echo "Memulai proses deployment ke server PRODUCTION..."
          echo "PERINGATAN: Menyentuh database produksi!"
          sleep 2
          echo "Menyiapkan rilis versi terbaru..."
          sleep 2
          echo "Mengalihkan traffic ke server baru tanpa downtime..."
          sleep 3
          echo "Dummy deployment ke Production berhasil!"
          echo "URL Production: https://www.b09.json-platform.com"