name: Staging CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build-and-test:
    name: Build, Test, and Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # actions/checkout@v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        # actions/setup-java@v4.7.0
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        # gradle/actions/setup-gradle@v4.3.0
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd576d0895c6a3b4345d3a9547

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Run Tests & Linters (Checkstyle & JaCoCo)
        working-directory: ./backend
        run: ./gradlew check

      - name: Upload Test Report
        # actions/upload-artifact@v4.4.3
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: failure()
        with:
          name: test-reports
          path: backend/build/reports/tests/test/

      - name: Upload Code Coverage Report
        # actions/upload-artifact@v4.4.3
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: always()
        with:
          name: jacoco-coverage-report
          path: backend/build/reports/jacoco/test/html/

      - name: Cache SonarQube packages
        # actions/cache@v4.2.0
        uses: actions/cache@1bd1e32a3ceb453115684670140fe0117d1459a8
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analyze with SonarCloud
        working-directory: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info